server:
  port: 8080


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /swagger.yaml
  api-docs:
    enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-db

  kafka:
    bootstrap-servers: localhost:9092
    #properties:
     # security.protocol: SASL_PLAINTEXT
     # sasl.mechanism: PLAIN
     # sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="pvZ1He5C7e";

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.value.default.type: com.ps.productservice.event.ProductCreatedEvent
      spring.json.trusted.packages: "com.ps.productservice.event, java.util, java.lang"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

# Additional Spring configuration
jackson:
  serialization:
    write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    com.ps.productservice: DEBUG

# Kafka Configuration (example)
kafka:
  topic:
    product: product-topic
    dlq: product-topic-dlq