server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true

jwt:
  secret: c2VjcmV0 #your_base64_encoded_secret_key_here
  expiration: 3600 # in seconds, e.g., 1 hour

logging:
  level:
    org.springframework: INFO
    com.ps.userservice: INFO

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /swagger.yaml
  api-docs:
    enabled: true

security:
  permit-all-paths:
    - /api/v1/users/**
    - /h2-console/**
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api-docs/**