server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your_secret_key_here
  expiration: 3600 # in seconds, e.g., 1 hour

logging:
  level:
    org.springframework: INFO
    com.ps.userservice: DEBUG

springfox:
  documentation:
    swagger:
      enabled: true

security:
  permit-all-paths:
    - /api/v1/users/login
    - /api/v1/users/register
    - /h2-console/**
    - /swagger-ui/**
    - /v3/api-docs/**