spring:
 cloud:
   gateway:
     routes:
       - id: user-management-service
         uri: http://localhost:8081
         predicates:
           - Path=/api/v1/users/**
         filters:
           - AuthenticationFilter
       - id: product-service
         uri: http://localhost:8082
         predicates:
           - Path=/api/v1/products/**
         filters:
           - AuthenticationFilter

 application:
   name: API-GATEWAY

jwt:
  secret: c2VjcmV0